server:
  port: 8080

spring:
  application:
    name: uniway-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/uniway_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

    # Esto hará que Hibernate actualice automáticamente el esquema
  
  # Configuración de email
  mail:
    host: smtp.gmail.com
    port: 587
    username: pruebanueva123456.123@gmail.com  #${MAIL_USERNAME:}
    password: umekocwbkcdalbjo  #${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  
  security:
    user:
      name: admin
      password: admin123

# Deshabilitar seguridad temporalmente
management:
  security:
    enabled: false

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Logging
logging:
  level:
    com.uniway: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method



